services:
  ecommerce_db:
     image: postgres:15
     container_name: ecommerce_db
     environment:
       POSTGRES_USER: mpac
       POSTGRES_PASSWORD: 0987
       POSTGRES_DB: ecommerce_db
     ports:
      - "5432:5432"
     volumes:
      - postgres_data:/var/lib/postgresql/data
 
   server:
     build:
       context: .
     container_name: ecommerce_server
     depends_on:
       - ecommerce_db
     ports:
      - "${SERVER_PORT}:${SERVER_PORT}" 
     environment:
       SERVER_PORT: 8080 
       DB_HOST: postgres_db 
       DB_PORT: 5432 
       DB_USER: mpac 
       DB_PASSWORD: 0987
       DB_NAME: ecommerce_db 
volumes:
  postgres_data:
~                                                                                             
~                   
